# Default values for certbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

certBot:
  isPrivateCluster: "false"
  hostBinding: 'Invalid Host Binding'
  privateTLS: "false"
  hostFqdn: 'Invalid Host FQDN'
  dnsAdminEmail: "techguru@byiq.com"
  environment: "staging"
  organization: "Invalid Organization"

replicaCount: 1

serviceAccount:
  create: true
  name: ''

rbac:
  create: true

certbotProtocolShare:
  cbProtocolVolumeName: "certbot-protocol"

certbotStateShare:
  cbStateVolumeClaimName: "certbot-state-pvc"
  cbStateVolumeName: "certbot-state"

certbotImage:
  repository: 'techguru/certbot'
  tag: '0.0.6'
  pullPolicy: IfNotPresent
  resources: {}

certbotInitImage:
  repository: 'techguru/certbot-init'
  tag: '0.0.6'
  pullPolicy: IfNotPresent
  resources: {}

nginxImage:
  repository: nginx
  tag: stable-alpine
  pullPolicy: IfNotPresent
  resources: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
  #  - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingress_test:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts: []
  #  - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
