{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "certbot.labels" . | indent 4 }}
  name: {{ template "certbot.serviceAccountName" . }}
{{- end -}}
