# Default values for cf-tls-certificate-manager-svc-docker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 'cfdevregistry.azurecr.io/cf-tls-certificate-manager-svc-docker'
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  # placeholder values should allow the service to install and minimally respond
  environment:
    ADMIN_EMAIL: 'techguru@byiq.com'
    APP_VERSION: '{{ .Chart.AppVersion }}'
    CERTIFICATE_CREATED_FLAG: "/etc/letsencrypt/certificate_created.flag"
    CERTIFICATE_DIR: '/etc/letsencrypt'
    CERTIFICATE_NAME: "cf-dev"
    CERTIFICATE_ORG: 'Acuity Brands, Inc.'
    DEV_CERTIFICATE_DIR: "/etc/letsencrypt/dev-cert"
    DEVELOPER_CERTIFICATE_REQUIRED_FLAG: "/etc/letsencrypt/developer_certificate_required.flag"
    HOST_DOMAIN: 'cf.dev.atrius-iot.com'
    IS_PRODUCTION: 'false'
    METRICS_PREFIX: 'cf.service.cf_tls_certificate_manager.'
    PRIVATE_TLS: 'false'
    RELEASE_NAME: 'cf-dev'
    RELEASE_NAMESPACE: 'cfk8s'
    RENEWAL_FAILED_FLAG: "/etc/letsencrypt/renewal_failed.flag"
    TLS_SECRET_NAME: 'waf-tls-secret'
  secrets:
    TLS_PEM: ''

certbot:
  protocol:
    volumeName: "certbot-protocol"
  state:
    volumeClaimName: "certbot-state-pvc"
    volumeName: "certbot-state"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingress_well_known:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
