{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "br-tls-certificate-manager-svc-docker.fullname" . }}
  labels:
    {{- include "br-tls-certificate-manager-svc-docker.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
{{- end -}}
