apiVersion: v1
kind: Service
metadata:
  name: {{ include "br-tls-certificate-manager-svc-docker.fullname" . }}
  labels:
    {{- include "br-tls-certificate-manager-svc-docker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "br-tls-certificate-manager-svc-docker.selectorLabels" . | nindent 4 }}
