apiVersion: v2
name: 'br-tls-certificate-manager-svc-docker'
description: 'CF: tls certificate manager service'
keywords:
  - 'connected-facilities'
  - 'br-tls-certificate-manager-svc'
type: application
home: ''  # The URL of this projects home page (optional)
sources: []  # A list of URLs to source code for this project (optional)
maintainers:
  - name: 'Paul Charlton'
    email: 'techguru@byiq.com'
    url: 'https://www.gitlab.com/techguru'
icon: ''
deprecated: false

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 'r1.1.4-dev'

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.1.4-dev
