apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cf-tls-certificate-manager-svc-docker.fullname" . }}
  labels:
  {{- include "cf-tls-certificate-manager-svc-docker.labels" . | nindent 4 }}
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
          {{- include "cf-tls-certificate-manager-svc-docker.selectorLabels" . | nindent 12 }}
          {{- if ( or .Values.config.environment .Values.config.secrets ) }}
          annotations:
            {{- if .Values.config.environment }}
            checksum/environment: {{ tpl (toYaml .Values.config.environment) . | sha256sum }}
            {{- end }}
            {{- if .Values.config.secrets }}
            checksum/secrets: {{ tpl (toYaml .Values.config.secrets) . | sha256sum }}
            {{- end }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "cf-tls-certificate-manager-svc-docker.serviceAccountName" . }}
          securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: '{{ template "cf-tls-certificate-manager-svc-docker.fullname" . }}-env'
                - secretRef:
                    name: '{{ template "cf-tls-certificate-manager-svc-docker.fullname" . }}-senv'
              env:
                - name: STATSD_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: STATSD_PORT
                  value: "8125"
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
