kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: 'cf-az-files-certbot-state-pvc'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '10G'
  storageClassName: 'manual-certbot'
  volumeMode: 'Filesystem'
  volumeName: 'cf-az-files-certbot-state-{{ .Release.Namespace }}-}pv'
