kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: 'certbot-state-pvc'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: 'sc-certbot-state'
