{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    {{ include "cf-tls-certificate-manager-svc-docker.labels" . | indent 4 }}
  name: {{ template "cf-tls-certificate-manager-svc-docker.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
{{- end -}}
